export const theme = {
  colors: {
    'Colors.Blue': '#3D53E7',
    'Colors.White.White-100': '#ffffff',
    'Colors.Greyscale.Grey-100': '#0f1013',
    'Colors.Text.Primary': 'rgba({Colors.Greyscale.Grey-100}, 0.87)',
    'Colors.Text.Secondary': 'rgba({Colors.Greyscale.Grey-100}, 0.60)',
    'Colors.Text.Disabled': 'rgba({Colors.Greyscale.Grey-100}, 0.38)',
    'Colors.Primary.Main': '$Colors.Blue',
    'Colors.Primary.Main-hover': '#384CD5',
    'Colors.Primary.Main-selected': '#3649CB',
    'Colors.Primary.Light': 'rgba($Colors.Primary.Main, 0.08)',
    'Colors.Primary.Light-hover': 'rgba($Colors.Primary.Main, 0.12)',
    'Colors.Primary.Light-selected': 'rgba($Colors.Primary.Main, 0.16)',
    'Colors.Primary.Outline-border': '$Colors.Primary.Main',
    'Colors.Primary.Contrast.High': '$Colors.White.White-100',
    'Colors.Primary.Contrast.Medium': 'rgba($Colors.White.White-100, 0.74)',
    'Colors.Primary.Contrast.Low': 'rgba($Colors.White.White-100, 0.48)',
    'Colors.Action.Main': 'rgba($Colors.Greyscale.Grey-100, 0.03)',
    'Colors.Action.Main-hover': 'rgba($Colors.Greyscale.Grey-100, 0.06)',
    'Colors.Action.Main-selected': 'rgba($Colors.Greyscale.Grey-100, 0.10)',
    'Colors.Action.Main-focus': 'rgba($Colors.Greyscale.Grey-100, 0.14)',
    'Colors.Action.Disabled-content': 'rgba($Colors.Greyscale.Grey-100, 0.26)',
    'Colors.Action.Disabled-background':
      'rgba($Colors.Greyscale.Grey-100, 0.12)',
    'Colors.Action.Active': 'rgba($Colors.Greyscale.Grey-100, 0.54)',
    'Colors.Other.Divider': 'rgba($Colors.Greyscale.Grey-100, 0.08)',
    'Colors.Other.Outline': 'rgba($Colors.Greyscale.Grey-100, 0.12)',
    'Colors.Other.Input-border': 'rgba($Colors.Greyscale.Grey-100, 0.42)',
    'Colors.Other.Overlay': 'rgba($Colors.Greyscale.Grey-100, 0.24)',
    'Colors.Error.Main': '#F44336',
    'Colors.Error.Main-hover': '#D73B30',
    'Colors.Error.Main-selected': '#CD382D',
    'Colors.Error.Light': 'rgba($Colors.Error.Main, 0.08)',
    'Colors.Error.Light-hover': 'rgba($Colors.Error.Main, 0.12)',
    'Colors.Error.Light-selected': 'rgba($Colors.Error.Main, 0.16)',
    'Colors.Error.Outline-border': 'rgba($Colors.Error.Main, 1)',
  },
}
