export const theme = {
  "colors": {
    "Colors.Blue.type": "#3D53E7",
    "Colors.White.White-100.type": "#ffffff",
    "Colors.Greyscale.Grey-100.type": "#0f1013",
    "Colors.Text.Primary.type": "rgba({Colors.Greyscale.Grey-100}, 0.87)",
    "Colors.Text.Secondary.type": "rgba({Colors.Greyscale.Grey-100}, 0.60)",
    "Colors.Text.Disabled.type": "rgba({Colors.Greyscale.Grey-100}, 0.38)",
    "Colors.Primary.Main.type": "$Colors.Blue",
    "Colors.Primary.Main-hover.type": "#384CD5",
    "Colors.Primary.Main-selected.type": "#3649CB",
    "Colors.Primary.Light.type": "rgba($Colors.Primary.Main, 0.08)",
    "Colors.Primary.Light-hover.type": "rgba($Colors.Primary.Main, 0.12)",
    "Colors.Primary.Light-selected.type": "rgba($Colors.Primary.Main, 0.16)",
    "Colors.Primary.Outline-border.type": "$Colors.Primary.Main",
    "Colors.Primary.Contrast.High.type": "$Colors.White.White-100",
    "Colors.Primary.Contrast.Medium.type": "rgba($Colors.White.White-100, 0.74)",
    "Colors.Primary.Contrast.Low.type": "rgba($Colors.White.White-100, 0.48)",
    "Colors.Action.Main.type": "rgba($Colors.Greyscale.Grey-100, 0.03)",
    "Colors.Action.Main-hover.type": "rgba($Colors.Greyscale.Grey-100, 0.06)",
    "Colors.Action.Main-selected.type": "rgba($Colors.Greyscale.Grey-100, 0.10)",
    "Colors.Action.Main-focus.type": "rgba($Colors.Greyscale.Grey-100, 0.14)",
    "Colors.Action.Disabled-content.type": "rgba($Colors.Greyscale.Grey-100, 0.26)",
    "Colors.Action.Disabled-background.type": "rgba($Colors.Greyscale.Grey-100, 0.12)",
    "Colors.Action.Active.type": "rgba($Colors.Greyscale.Grey-100, 0.54)",
    "Colors.Other.Divider.type": "rgba($Colors.Greyscale.Grey-100, 0.08)",
    "Colors.Other.Outline.type": "rgba($Colors.Greyscale.Grey-100, 0.12)",
    "Colors.Other.Input-border.type": "rgba($Colors.Greyscale.Grey-100, 0.42)",
    "Colors.Other.Overlay.type": "rgba($Colors.Greyscale.Grey-100, 0.24)",
    "Colors.Error.Main.type": "#F44336",
    "Colors.Error.Main-hover.type": "#D73B30",
    "Colors.Error.Main-selected.type": "#CD382D",
    "Colors.Error.Light.type": "rgba($Colors.Error.Main, 0.08)",
    "Colors.Error.Light-hover.type": "rgba($Colors.Error.Main, 0.12)",
    "Colors.Error.Light-selected.type": "rgba($Colors.Error.Main, 0.16)",
    "Colors.Error.Outline-border.type": "rgba($Colors.Error.Main, 1)"
  }
}